xinit arg, svelte vim, tailcat

diff --git a/roles/arch-i3-desktop/files/i3xinitrc b/roles/arch-i3-desktop/files/i3xinitrc
--- a/roles/arch-i3-desktop/files/i3xinitrc
+++ b/roles/arch-i3-desktop/files/i3xinitrc
@@ -8,13 +8,6 @@ sysmodmap=/etc/X11/xinit/.Xmodmap
 # merge in defaults and keymaps
 
 if [ -f $sysresources ]; then
-
-
-
-
-
-
-
     xrdb -merge $sysresources
 
 fi
@@ -24,15 +17,7 @@ if [ -f $sysmodmap ]; then
 fi
 
 if [ -f "$userresources" ]; then
-
-
-
-
-
-
-
     xrdb -merge "$userresources"
-
 fi
 
 if [ -f "$usermodmap" ]; then
@@ -48,4 +33,14 @@ if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  unset f
 fi
 
-exec i3
+if [ -z "$@" ]; then
+    echo "ERROR: No command provided. Examples: '$0 i3' '$0 openbox-session'"
+    exit 1
+fi
+
+# export vars used by WM
+# TERMINAL: used in i3-sensible-terminal
+export TERMINAL=alacritty
+
+# start cmd
+exec $@
