Use curl-newer for somafm fetching

diff --git a/roles/dots/files/bin/curl-newer b/roles/dots/files/bin/curl-newer
--- a/roles/dots/files/bin/curl-newer
+++ b/roles/dots/files/bin/curl-newer
@@ -10,13 +10,18 @@ fi
 
 TRACKING_DIR="${TMPDIR:-/tmp}/curl-newer"
 CACHED_FILE="$TRACKING_DIR/$FILE_KEY"
+CACHED_FILE_ERR="$TRACKING_DIR/${FILE_KEY}_err"
 
 SECONDS="${1-0}"
 shift 1
 
 DO_FETCH=
 
-if [[ ! -s "$CACHED_FILE" ]]; then
+if [[ -s "$CACHED_FILE_ERR" ]]; then
+    # if last attempt was an error, always fetch
+    DO_FETCH=1
+elif [[ ! -s "$CACHED_FILE" ]]; then
+    # if no existing cached file, fetch
     DO_FETCH=1
 else
     # date of cache is < now
@@ -32,4 +37,11 @@ if [[ "$DO_FETCH" ]]; then
     echo ">> Fetching $CACHED_FILE" 1>&2
     mkdir -p "$TRACKING_DIR"
     curl -o "$CACHED_FILE" -L "$@"
+    rc=$?
+    if [[ $rc != 0 ]]; then
+        echo ">> Error $rc, marking $CACHED_FILE_ERR so next try will fetch" 1>&2
+        touch "$CACHED_FILE_ERR"
+    fi
 fi
+
+echo "$CACHED_FILE"
